---
# tasks file for k3s-gateway/cert-manager

- name: Copia manifiesto de recurso namespace para cert-manager
  ansible.builtin.template:
    src: cert-manager-namespace.yml.j2
    dest: /tmp/cert-manager-namespace.yml
    owner: root
    group: root
    mode: '0640'
  changed_when: false

- name: Instala recurso namespace para cert-manager
  ansible.builtin.shell: kubectl apply -f /tmp/cert-manager-namespace.yml
  changed_when: false

- name: Agregar repositoro helm cert-manager
  kubernetes.core.helm_repository:
    name: jetstack
    repo_url: https://charts.jetstack.io

- name: Desplegar el controlador cert-manager
  kubernetes.core.helm:
    name: cert-manager
    chart_ref: jetstack/cert-manager
    release_namespace: "{{ cert_manager_namespace }}"
    values:
      installCRDs: true
    state: present
  become: false

- name: Esperar hasta que el servicio cert-manager inicialice
  kubernetes.core.k8s_info:
    kind: Deployment
    name: cert-manager
    namespace: "{{ cert_manager_namespace }}"
    wait: true
    wait_sleep: 10
    wait_timeout: 210
  become: false

- name: Copia manifiesto de recurso clusterissuer root ca para cert-manager
  ansible.builtin.template:
    src: cert-manager-root-ca.yml.j2
    dest: /tmp/cert-manager-root-ca.yml
    owner: root
    group: root
    mode: '0640'
  changed_when: false

- name: Instala recurso clusterissuer root ca para cert-manager
  ansible.builtin.shell: kubectl apply -f /tmp/cert-manager-root-ca.yml
  changed_when: false

- name: Copia manifiesto de recurso clusterissuer intermediate ca para cert-manager
  ansible.builtin.template:
    src: cert-manager-intermediate-ca1.yml.j2
    dest: /tmp/cert-manager-intermediate-ca1.yml
    owner: root
    group: root
    mode: '0640'
  changed_when: false

- name: Instala recurso clusterissuer intermediate ca para cert-manager
  ansible.builtin.shell: kubectl apply -f /tmp/cert-manager-intermediate-ca1.yml
  changed_when: false
