---
# tasks file for k3s-gateway/get-root-ca-certs

- name: Asegurar que el directorio de salida para los certificados existe
  ansible.builtin.file:
    path: "{{ ca_output_dir }}"
    state: directory
    owner: root
    group: root
    mode: '0750'

- name: Obtener certificado raíz (tls.crt) desde secret de cert-manager
  ansible.builtin.shell: |
    kubectl get secret {{ ca_secret_name }} -n {{ cert_manager_namespace }} \
      -o jsonpath="{.data['tls\.crt']}" | \
      base64 -d > {{ ca_output_dir }}/{{ ca_output_file }}
  args:
    executable: /bin/bash
  changed_when: true

- name: Verificar que el certificado se ha escrito correctamente
  ansible.builtin.stat:
    path: "{{ ca_output_dir }}/{{ ca_output_file }}"
  register: cert_stat

- name: Mostrar listado de certificados
  ansible.builtin.debug:
    msg: "Certificado raíz exportado a {{ ca_output_dir }}/{{ ca_output_file }}"
  when: cert_stat.stat.exists

- name: Registrar CA como confiable en el sistema (update-ca-certificates)
  ansible.builtin.command: update-ca-certificates
  when: cert_stat.stat.exists
  changed_when: true

- name: Copiar certificado raíz a control node para distribución
  ansible.builtin.fetch:
    src: "{{ ca_output_dir }}/{{ ca_output_file }}"
    dest: "{{ ca_custom_dir }}/{{ ca_output_file }}"
    flat: true
  when: cert_stat.stat.exists
