---
# tasks file for k3s-gateway/ingress-nginx

- name: Copia manifiesto de recurso namespace para ingress-nginx
  ansible.builtin.template:
    src: ingress-nginx-namespace.yml.j2
    dest: /tmp/ingress-nginx-namespace.yml
    owner: root
    group: root
    mode: '0640'
  changed_when: false

- name: Instala recurso namespace para ingress-nginx
  ansible.builtin.shell: kubectl apply -f /tmp/ingress-nginx-namespace.yml
  changed_when: false

- name: Agregar repositoro helm ingress-nginx
  kubernetes.core.helm_repository:
    name: ingress-nginx
    repo_url: https://kubernetes.github.io/ingress-nginx

- name: Instalar el controlador ingress-nginx
  kubernetes.core.helm:
    name: ingress
    chart_ref: ingress-nginx/ingress-nginx
    release_namespace: "{{ ingress_nginx_namespace }}"
    values:
      controller.ingressClass: "{{ ingress_nginx_ingress_class }}"
      controller.service.externalTrafficPolicy: "{{ ingress_nginx_external_traffic_policy }}"
      controller.publishService.enabled: "{{ ingress_nginx_publish_service_enabled }}"
      controller.replicaCount: "{{ ingress_nginx_replica_count }}"
      controller.minAvailable: "{{ ingress_nginx_min_available }}"
      defaultBackend.enabled: "{{ ingress_nginx_default_backend_enabled }}"
  become: false

- name: Esperar hasta que el servicio ingress-nginx inicialice
  kubernetes.core.k8s_info:
    kind: Deployment
    name: ingress-ingress-nginx-controller
    namespace: "{{ ingress_nginx_namespace }}"
    wait: true
    wait_sleep: 10
    wait_timeout: 210
  become: false
