---
# tasks file for k3s-gateway/metallb

- name: Copia manifiesto de recurso namespace para metallb
  ansible.builtin.template:
    src: metallb-namespace.yml.j2
    dest: /tmp/metallb-namespace.yml
    owner: root
    group: root
    mode: '0640'
  changed_when: false

- name: Instala recurso namespace para metallb
  ansible.builtin.shell: kubectl apply -f /tmp/metallb-namespace.yml
  changed_when: false

- name: Agregar repositoro helm metallb
  kubernetes.core.helm_repository:
    name: metallb
    repo_url: https://metallb.github.io/metallb

- name: Instalar helm chart de metallb
  kubernetes.core.helm:
    name: metallb
    chart_ref: metallb/metallb
    release_namespace: "{{ metallb_namespace }}"
  become: false

- name: Esperar hasta que el servicio metallb-controller inicialice
  kubernetes.core.k8s_info:
    kind: Deployment
    name: metallb-controller
    namespace: metallb
    wait: true
    wait_sleep: 10
    wait_timeout: 210
  become: false

- name: Copia manifiesto de IPAddressPool para metallb
  ansible.builtin.template:
    src: metallb-ipaddresspool.yml.j2
    dest: /tmp/metallb-ipaddresspool.yml
    owner: root
    group: root
    mode: '0640'

- name: Instala recurso IPAddressPool para metallb
  ansible.builtin.shell: kubectl apply -f /tmp/metallb-ipaddresspool.yml
  changed_when: false

- name: Copia manifiesto de L2Advertisement para metallb
  ansible.builtin.template:
    src: metallb-l2advertisement.yml.j2
    dest: /tmp/metallb-l2advertisement.yml
    owner: root
    group: root
    mode: '0640'

- name: Instala recurso L2Advertisement para metallb
  ansible.builtin.shell: kubectl apply -f /tmp/metallb-l2advertisement.yml
  changed_when: false
