---
# tasks file for nfs-client
- name: Instalar el cliente NFS
  ansible.builtin.apt:
    name:
      - nfs-common

- name: Crear directorio para recurso NFS backup
  ansible.builtin.file:
    path: "{{ nfs_share_backup }}"
    owner: root
    group: root
    state: directory
    mode: 0777

- name: Configurar automontaje de recurso NFS backup
  ansible.posix.mount:
    name: "{{ nfs_share_backup }}"
    src: "{{ nfs_server }}:{{ nfs_path_backup }}"
    fstype: nfs
    opts: "rw"
    dump: "0"
    passno: "0"
    state: mounted

- name: Crear directorio para recurso NFS media
  ansible.builtin.file:
    path: "{{ nfs_share_media }}"
    owner: root
    group: root
    state: directory
    mode: 0777

- name: Configurar automontaje de recurso NFS media
  ansible.posix.mount:
    name: "{{ nfs_share_media }}"
    src: "{{ nfs_server }}:{{ nfs_path_media }}"
    fstype: nfs
    opts: "rw"
    dump: "0"
    passno: "0"
    state: mounted
