---
# tasks file for samba-server

- name: Instala el servidor Samba
  ansible.builtin.apt:
    name: samba
    state: present

- name: Crea el directorio público compartido
  ansible.builtin.file:
    path: "{{ samba_public_shared_path }}"
    state: directory
    mode: "{{ samba_create_mask }}"
    owner: pi
    group: pi

- name: Crea el directorio privado compartido
  ansible.builtin.file:
    path: "{{ samba_private_shared_path }}"
    state: directory
    mode: "{{ samba_create_mask }}"
    owner: pi
    group: pi

- name: Configura el servidor Samba
  ansible.builtin.template:
    src: smb.conf.j2
    dest: /etc/samba/smb.conf
    owner: root
    group: root
    mode: '0644'
  notify:
    - Restart smbd
    - Restart nmbd

- name: Añade usuarios Samba
  loop: "{{ samba_users }}"
  command: >
    (echo '{{ item.password }}'; echo '{{ item.password }}') |
    smbpasswd -a -s '{{ item.username }}'
  when: item.password is defined
