---
- name: Asegurar que el directorio .kube existe para el usuario {{ k3s_admin_user }}
  ansible.builtin.file:
    path: "/home/{{ k3s_admin_user }}/.kube"
    state: directory
    owner: "{{ k3s_admin_user }}"
    group: "{{ k3s_admin_user }}"
    mode: '0700'

- name: Copiar config de Kubernetes a usuario {{ k3s_admin_user }}
  ansible.builtin.copy:
    src: /etc/rancher/k3s/k3s.yaml
    dest: "/home/{{ k3s_admin_user }}/.kube/config"
    owner: "{{ k3s_admin_user }}"
    group: "{{ k3s_admin_user }}"
    mode: '0600'
    remote_src: true

- name: Reemplazar IP del API server si se accede de forma remota
  ansible.builtin.replace:
    path: "/home/{{ k3s_admin_user }}/.kube/config"
    regexp: 'https://127\.0\.0\.1:[0-9]+'
    replace: "https://{{ ansible_host }}:6443"
  when: replace_apiserver_address

- name: Crea script para configuraciones kubectl
  ansible.builtin.file:
    path: '/etc/profile.d/kubeconfig.sh'
    owner: root
    group: root
    mode: "0644"
    state: touch

- name: Configura env KUBECONFIG
  ansible.builtin.lineinfile:
    dest: "/etc/profile.d/kubeconfig.sh"
    state: present
    regexp: "^export KUBECONFIG="
    line: "export KUBECONFIG=/home/{{ k3s_admin_user }}/.kube/config"

- name: Configura autocompletado para kubectl
  ansible.builtin.lineinfile:
    dest: "/etc/profile.d/kubeconfig.sh"
    state: present
    regexp: "^source <(kubectl completion bash)"
    line: "source <(kubectl completion bash)"

- name: Configura alias kubectl
  ansible.builtin.lineinfile:
    dest: "/etc/profile.d/kubeconfig.sh"
    state: present
    regexp: '^alias k="kubectl"'
    line: 'alias k="kubectl"'

- name: Configura autocompletado para alias kubectl
  ansible.builtin.lineinfile:
    dest: "/etc/profile.d/kubeconfig.sh"
    state: present
    regexp: '^complete -F __start_kubectl k'
    line: 'complete -F __start_kubectl k'

- name: Descargar kubeconfig desde el servidor remoto
  ansible.builtin.fetch:
    src: "/home/{{ k3s_admin_user }}/.kube/config"
    dest: "{{ inventory_dir }}/.kube/{{ inventory_hostname }}.kubeconfig"
    flat: true
