---
- name: Asegurar que el directorio .kube existe para el usuario {{ k3s_admin_user }}
  ansible.builtin.file:
    path: "/home/{{ k3s_admin_user }}/.kube"
    state: directory
    owner: "{{ k3s_admin_user }}"
    group: "{{ k3s_admin_user }}"
    mode: '0700'

- name: Copiar config de Kubernetes a usuario {{ k3s_admin_user }}
  ansible.builtin.copy:
    src: /etc/rancher/k3s/k3s.yaml
    dest: "/home/{{ k3s_admin_user }}/.kube/config"
    owner: "{{ k3s_admin_user }}"
    group: "{{ k3s_admin_user }}"
    mode: '0600'
    remote_src: true

- name: Reemplazar IP del API server si se accede de forma remota
  ansible.builtin.replace:
    path: "/home/{{ k3s_admin_user }}/.kube/config"
    regexp: 'https://127\.0\.0\.1:[0-9]+'
    replace: "https://{{ ansible_host }}:6443"
  when: replace_apiserver_address
