---
# tasks file for k3s-server

- name: Desactivar memoria swap
  command: dphys-swapfile swapoff
  register: swapoffoutput
  changed_when: swapoffoutput.rc != 0
  failed_when: swapoffoutput.rc != 0

- name: Eliminar archivo swapfile
  command: dphys-swapfile uninstall
  register: swapfileuninsoutput
  changed_when: swapfileuninsoutput.rc != 0
  failed_when: swapfileuninsoutput.rc != 0

- name: Capturar estado de memoria swap
  command: free -m
  register: freeoutput
  changed_when: freeoutput.rc != 0
  failed_when: freeoutput.rc != 0

- name: Mostrar estado de memoria swap
  debug: var=freeaoutput.stdout_lines

- name: Desactivar el servicio dphys-swapfile
  service:
    name: dphys-swapfile.service
    state: stopped
    enabled: false

- name: Limpiar reglas firewall iptables
  iptables:
    flush: true

- name: Configurar alternativa de iptables a iptables-legacy
  alternatives:
    name: iptables
    path: /usr/sbin/iptables-legacy

- name: Configurar alternativa de ip6tables a ip6tables-legacy
  alternatives:
    name: ip6tables
    path: /usr/sbin/ip6tables-legacy

- name: Instalar servidor k3s
  shell: curl -sfL https://get.k3s.io | INSTALL_K3S_CHANNEL={{ k3s_channel }} sh -s - --write-kubeconfig-mode 644 --disable traefik --disable servicelb
  changed_when: false

- name: Get server token
  command: cat /var/lib/rancher/k3s/server/node-token
  changed_when: false

- name: Taint nodo maestro para no schedule
  command: kubectl taint --overwrite node k3s-master node-role.kubernetes.io/master=true:NoSchedule
  register: taintoutput
  changed_when: taintoutput.rc != 0
  failed_when: taintoutput.rc != 0
