---
# tasks file for k3s-server

- name: Instalar servidor k3s
  ansible.builtin.shell: curl -sfL https://get.k3s.io | INSTALL_K3S_CHANNEL={{ k3s_channel }} sh -s - --write-kubeconfig-mode 600 --disable traefik --disable servicelb
  changed_when: false

- name: Esperar 30 secs mientras el servidor inicializa
  ansible.builtin.command: sleep 30
  register: sleepoutput
  changed_when: sleepoutput.rc != 0
  failed_when: sleepoutput.rc != 0

- name: Taint nodo maestro para no schedule
  ansible.builtin.command: kubectl taint --overwrite node {{ inventory_hostname_short }} node-role.kubernetes.io/master=true:NoSchedule
  register: taintoutput
  changed_when: taintoutput.rc != 0
  failed_when: taintoutput.rc != 0
  when: k3s_taint_control_plane

- name: Incluir tareas de configuración de kubeconfig
  ansible.builtin.import_tasks: kubeconfig.yml
