---
# tasks file for k3s-server

- name: Incluir tareas de despliegue de cluster k3s
  ansible.builtin.import_tasks: server.yml

- name: Incluir tareas de configuración de kubeconfig
  ansible.builtin.import_tasks: kubeconfig.yml
