---
# defaults file for usb-storage
partitions:
  - label: "kmx-shared"
    filesystem: "exfat"
    mount_point: "/mnt/kmx-shared"
    opts: "defaults"
    owner: "root"
    group: "root"
    mode: "0755"
  - label: "kmx-media"
    filesystem: "btrfs"
    mount_point: "/mnt/kmx-media"
    opts: "autodefrag"
    owner: "root"
    group: "root"
    mode: "0755"
  - label: "kmx-backup"
    filesystem: "xfs"
    mount_point: "/mnt/kmx-backup"
    opts: "defaults"
    owner: "root"
    group: "root"
    mode: "0750"
