---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    environment: prod
    owner: yorch
    service: whoami
    component: api
  name: whoami-app-prod
  namespace: argocd
spec:
  destination:
    namespace: whoami
    server: https://10.101.165.13:6443
  project: platform
  source:
    path: kubernetes/prod/whoami
    repoURL: https://github.com/jorgearma1982/infra-home.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
