---
# tasks file for cgroups

- name: Agregar soporte cgroups de cpu y memoria al kernel
  lineinfile:
    path: /boot/cmdline.txt
    backrefs: true
    regexp: '^(.*)rootwait$'
    line: '\1rootwait cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory'
  notify: restart server
