---
# tasks file for k3s-helm

- name: Descargar instalador de helm
  get_url:
    url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
    dest: /tmp/get-helm.sh
    mode: 0700

- name: Instalar helm
  shell: /tmp/get-helm.sh
  changed_when: false

- name: Limpiar instalador de helm
  file:
    path: /tmp/get-helm.sh
    state: absent

- name: Crear directorio configuración kubectl
  file:
    path: '/home/pi/.kube'
    state: directory
    owner: pi
    group: pi
    mode: 0700

- name: Obtener archivo de configuración kubectl
  copy:
    src: '/etc/rancher/k3s/k3s.yaml'
    dest: '/home/pi/.kube/config'
    remote_src: true
    owner: pi
    group: pi
    mode: 0600

- name: Crea script para env KUBECONFIG
  file:
    path: '/etc/profile.d/kubeconfig.sh'
    owner: root
    group: root
    mode: 0644
    state: touch

- name: Configura env KUBECONFIG
  lineinfile:
    dest: "/etc/profile.d/kubeconfig.sh"
    state: present
    regexp: "^export KUBECONFIG="
    line: "export KUBECONFIG=/home/pi/.kube/config"

- name: Agregar repositoro helm metallb
  command: helm repo add metallb https://metallb.github.io/metallb
  changed_when: false
  become: false

- name: Actualizar repositorios helm con metallb
  command: helm repo update
  changed_when: false
  become: false

- name: Instalar metallb
  shell: |
    helm ls -n kube-system | grep metallb || helm install metallb metallb/metallb \
      --namespace kube-system \
      --set configInline.address-pools[0].name=default \
      --set configInline.address-pools[0].protocol=layer2 \
      --set configInline.address-pools[0].addresses[0]=10.101.114.240-10.101.114.250
  changed_when: false
  become: false

- name: Agregar repositoro helm ingress-nginx
  command: helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
  changed_when: false
  become: false

- name: Actualizar repositorios helm con ingress-nginx
  command: helm repo update
  changed_when: false
  become: false

- name: Instalar nginx
  shell: |
    helm ls -n kube-system | grep ingress || helm install ingress ingress-nginx/ingress-nginx \
      --namespace kube-system \
      --set controller.ingressClass=nginx \
      --set controller.publishService.enabled=true \
      --set controller.replicaCount=2 \
      --set controller.minAvailable=1 \
      --set controller.externalTrafficPolicy=Local \
      --set defaultBackend.enabled=false
  changed_when: false
  become: false

- name: Agregar namespace argocd
  shell: kubectl get ns argocd || kubectl create namespace argocd
  changed_when: false
  become: false

- name: Agregar repositoro helm argo-cd
  command: helm repo add argo https://argoproj.github.io/argo-helm
  changed_when: false
  become: false

- name: Actualizar repositorios helm con argo-cd
  command: helm repo update
  changed_when: false
  become: false

- name: Instalar argocd
  shell: |
    helm ls -n argocd | grep argo || helm install argo-cd argo/argo-cd \
      --namespace argocd
  changed_when: false
  become: false
