---
galaxy_info:
  role_name: ssh_server
  author: Jorge Armando Medina
  description: Tasks for setting up local ssh service
  company: KronOps
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - focal
  galaxy_tags:
    - networking
dependencies: []
