---
# tasks file for general-settings

- name: Configurar el nombre de host a nivel kernel
  ansible.builtin.hostname: name={{ hostname_name }}

- name: Configurar el nombre de host persistente
  ansible.builtin.copy:
    content: "{{ hostname_name }}"
    dest: /etc/hostname
    force: true
    mode: 0644
  when: hostname_name is defined

- name: Configurar resolución de nombres local
  ansible.builtin.template:
    src: default-hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644
    backup: true

- name: Instalar paquete de zonas horarias
  ansible.builtin.apt:
    name:
      - tzdata
    state: present

- name: Configurar zona horaria
  community.general.timezone:
    name: "{{ timezone }}"
