---
galaxy_info:
  role_name: ntp_client
  author: Jorge Medina
  description: Install ntp client on linux server
  company: KronOps
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Debian
      versions:
        - buster
  galaxy_tags:
    - system
    - networking
dependencies: []
