---
galaxy_info:
  role_name: k8s_tools
  author: Jorge Armando Medina
  description: Tareas para configurar herramientas de kubernetes para shell
  company: KronOps
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Debian
      versions:
        - bookworm
  galaxy_tags:
    - system
    - cloud
dependencies: []
