---
- name: Deploy | k3s-master
  hosts: master
  become: true
  pre_tasks:
    - name: Actualizar paquetes del sistema
      ansible.builtin.apt:
        update_cache: "yes"
        upgrade: "yes"
  roles:
    - general-settings
    - shell-tools
    - ntp-client
    - ssh-server
    - iptables-legacy
    - role: cgroups
      when: >
        (ansible_architecture == "aarch64") or
        (ansible_distribution == "Raspbian" and
         ansible_distribution_version is version('12', '>='))
    - role: disable-swapfile
      when: >
        (ansible_architecture == "aarch64") or
        (ansible_distribution == "Raspbian" and
         ansible_distribution_version is version('12', '>='))
    - k3s-server
    - k8s-tools
  post_tasks:
    - name: Limpiar paquetes del cache
      ansible.builtin.apt:
        autoclean: "yes"
        autoremove: "yes"
