---
# Deploy k3s-workers
- hosts: workers
  become: true
  pre_tasks:
    - name: Actualizar paquetes del sistema
      apt:
        update_cache: "yes"
        upgrade: "yes"

  roles:
    - general-settings
    - ntp-client
    - ssh-server
    - cgroups
    - nfs-client
    - k3s-agent

  post_tasks:
    - name: Limpiar paquetes del cache
      apt:
        autoclean: "yes"
        autoremove: "yes"

# Deploy k3s-master
- hosts: master
  become: true
  tasks:
    - name: Etiquetar nodos k3s-worker1 como workers
      shell: kubectl label node k3s-worker1 node-role.kubernetes.io/worker=''
    - name: Etiquetar nodos k3s-worker2 como workers
      shell: kubectl label node k3s-worker2 node-role.kubernetes.io/worker=''
