---
- name: Despliegue | SSH keys
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Despliega llave ssh de ansible a servidores
      ansible.posix.authorized_key:
        user: "{{ ansible_user }}"
        key: "{{ lookup('file', 'inventory/.ssh/id_ansible_ed25519.pub') }}"
        state: present
