---
- name: Deploy | k3s-master
  hosts: master
  become: true
  pre_tasks:
    - name: Actualizar paquetes del sistema
      ansible.builtin.apt:
        update_cache: "yes"
        upgrade: "yes"
  roles:
    - general-settings
    - shell-tools
    - ntp-client
    - ssh-server
    - iptables-legacy
    - { role: cgroups, when: run_arm_or_rpi }
    - { role: disable-swapfile, when: run_arm_or_rpi }
    - k3s-server
  post_tasks:
    - name: Limpiar paquetes del cache
      ansible.builtin.apt:
        autoclean: "yes"
        autoremove: "yes"
