---
- name: Genera configuración de kubeconfig de clusters k3s
  hosts: localhost
  connection: local
  become: false
  environment:
    HOME: "{{ lookup('env', 'HOME') }}"
  vars:
    kubeconfig_dir: "{{ lookup('env', 'HOME') }}/.kube"
    kubeconfig_file: "{{ lookup('env', 'HOME') }}/.kube/config"

  tasks:
    - name: Asegurar directorio de KUBECONFIG existe
      ansible.builtin.file:
        path: "{{ kubeconfig_dir }}"
        state: directory
        mode: '0750'

    - name: Fusionar kubeconfigs remotos en ~/.kube/config local
      ansible.builtin.shell: |
        export KUBECONFIG=$(find "inventory/.kube" -name '*.kubeconfig' | paste -sd:)
        kubectl config view --flatten > "{{ kubeconfig_file }}"
      args:
        executable: /bin/bash
      changed_when: false
