---
# tasks file for k3s-agent

- name: Instalar agente k3s
  ansible.builtin.shell: curl -sfL https://get.k3s.io | K3S_URL=https://{{ k3s_server_url }} K3S_TOKEN_FILE={{ k3s_server_token }} sh -
  changed_when: false

- name: Esperar 30 secs mientras los agentes inicializan
  ansible.builtin.command: sleep 30
  register: sleepoutput
  changed_when: sleepoutput.rc != 0
  failed_when: sleepoutput.rc != 0
