---
# defaults file for samba-server

samba_server_string: "NAS 01"
samba_workgroup: "HQ"
samba_netbios_name: "NAS01"
samba_public_shared_name: "Publico"
samba_public_shared_path: "/home/pi/publico"
samba_private_shared_name: "Privado"
samba_private_shared_path: "/home/pi/privado"
samba_create_mask: '0777'
samba_directory_mask: '0777'
samba_group_name: "homelab"
samba_users:
  - { username: "pi", password: "CHANGEME" }
