---
# defaults file for samba-server

samba_server_string: "NAS 01"
samba_workgroup: "HQ"
samba_netbios_name: "NAS01"
samba_public_shared_name: "CompartidoPublico"
samba_public_shared_path: "/home/pi/compartido_publico"
samba_private_shared_name: "CompartidoPrivado"
samba_private_shared_path: "/home/pi/compartido_privado"
samba_create_mask: '0777'
samba_directory_mask: '0777'
samba_users:
  - { username: "pi", password: "CHANGEME" }
