---
# tasks file for ntp-client

- name: Configura el servidor NTP en timesyncd
  ansible.builtin.lineinfile:
    path: /etc/systemd/timesyncd.conf
    line: 'NTP={{ ntp_server }}'
    create: true
    mode: "0644"
    state: present
  notify:
    - restart systemd-timesyncd

- name: Iniciar y habilitar servicio systemd-timesyncd
  ansible.builtin.service:
    name: systemd-timesyncd
    state: started
    enabled: true
