---
galaxy_info:
  role_name: general_settings
  author: Jorge Armando Medina
  description: Common tasks for setting up general settings for Linux servers
  company: KronOps
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Debian
      versions:
        - bookworm
  galaxy_tags:
    - system
dependencies: []
