---
# tasks file for shell-tools

- name: Instala herramientas del shell para archivos
  ansible.builtin.apt:
    name: "{{ file_packages }}"
    state: present

- name: Instala herramientas del shell para red
  ansible.builtin.apt:
    name: "{{ net_packages }}"
    state: present

- name: Instala herramientas del shell para administración
  ansible.builtin.apt:
    name: "{{ admin_packages }}"
    state: present

- name: Verifica homes existentes de usuarios admin
  ansible.builtin.stat:
    path: "{{ item.home }}"
  loop: "{{ admin_users }}"
  loop_control:
    label: "{{ item.home }}"
  register: admin_user_homes

- name: Instala archivo de configuración de vim para usuarios admin
  ansible.builtin.copy:
    src: "dotvimrc"
    dest: "{{ item.item.home }}/.vimrc"
    owner: "{{ item.item.name }}"
    group: "{{ item.item.group }}"
    mode: "0600"
  loop: "{{ admin_user_homes.results }}"
  loop_control:
    label: "{{ item.item.home }}"
  when: item.stat.exists

- name: Instala archivo de configuración para gnu screen para usuarios admin
  ansible.builtin.copy:
    src: "dotscreenrc"
    dest: "{{ item.item.home }}/.screenrc"
    owner: "{{ item.item.name }}"
    group: "{{ item.item.group }}"
    mode: "0600"
  loop: "{{ admin_user_homes.results }}"
  loop_control:
    label: "{{ item.item.home }}"
  when: item.stat.exists
