name: CI

on:
  pull_request:
    branches: [ main ]

env:
  PROJECT: infra-home

jobs:
  build-and-test:
    name: Build and test
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Yamllint
    - uses: ibiqlik/action-yamllint@v3
      with:
        format: parsable
        strict: true
    - name: Check master playbook
      run: cd ansible; ansible-playbook --syntax-check deploy-k3s-master.yml
    - name: Check workers playbook
      run: cd ansible; ansible-playbook --syntax-check deploy-k3s-workers.yml
