name: CI

on:
  pull_request:
    branches: [ main ]

env:
  PROJECT: infra-home

jobs:
  build-and-test:
    name: Build and test
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Lint check yaml files
      uses: ibiqlik/action-yamllint@v3
      with:
        format: parsable
        strict: true
    - name: Syntax check & Lint ansible files
      run: |
        cd ansible; ansible-lint deploy-k3s-master.yml
        cd ansible; ansible-playbook --syntax-check deploy-k3s-master.yml
        cd ansible; ansible-lint deploy-k3s-workers.yml
        cd ansible; ansible-playbook --syntax-check deploy-k3s-workers.yml
